source "https://rubygems.org"

gem "middleman", "~>3.2.1"
gem "middleman-livereload"
gem "middleman-smusher"
gem "eco"
gem "compass-rgbapng"
gem "compass-css-arrow"
gem "rb-fsevent", "~> 0.9.0"
gem "rake", ">= 0.9.2.2"
